# Generated by Django 4.1 on 2022-09-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_post_image_alter_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
