# Generated by Django 4.1 on 2022-10-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
