# Generated by Django 4.1 on 2022-10-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_perfil_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perfil',
        ),
    ]
