# Generated by Django 4.1 on 2022-10-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBlog', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='imgPort',
            field=models.ImageField(blank=True, default='pro2.jpeg', null=True, upload_to='avatares'),
        ),
    ]
